*** NASTY BUG:  calling pipeline in a loop agaisnt an open file truncates it each exec
    ouch, this happens with subprocess.call_check too


- TSV levels:
  - Row - container for a row
  - Reader -

- document generators:
  http://codespeak.net/~mwh/pydoctor/ - discussion of others

- 2bit parser:
  https://github.com/tomclegg/get-evidence/blob/master/server/utils/twobit.py
      - requires cython, Ian had good luck
          I had to make the following change on line 111 of the .pyx file for it
          to handle Ns properly:

              memset(dna + s - fragStart, 'N'[0], e - s) -> memset(dna + s - fragStart, c'N', e - s)
- rename pycbio.sys, it prevent moving PycbioException up one level, since PycbioException imports
  standard sys. Specifying absolute import still breaks pipeline because pickle of exceptions doesn't
  work.


- reverse asserts so order is expect, got (corresponds to diff outout, see pslMapTests)
